import './globals.css';
export const metadata = {
  title: 'CFG Parser',
  description: 'Generated by Next.js',
};
 
export default function RootLayout({ children }) {
  return (
    <html lang="en" className='scroll-smooth'>
      <body>{children}</body>
    </html>
  );
}